package com.echoboard.exception;

public enum ErrorCode {
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_REFRESH_TOKEN,
    INVALID_SESSION_STATUS,
    INVALID_QUESTION_STATUS,
    WEBSOCKET_AUTHENTICATION_FAILED,
    WEBSOCKET_AUTHORIZATION_FAILED,
    DUPLICATE_RESOURCE,
    INVALID_POLL_STATUS
}
